name: mastofeed

on:

  # uncomment the following 2 lines so that it runs automatically every hour
  # schedule:
  #   - cron: '1 * * * *' 
  workflow_dispatch:

jobs:
  check-feed:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content
        with:
          persist-credentials: false 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: create working directory
        shell: bash
        run: |
          mkdir out

      - name: download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: control-imported
          path: out
          if_no_artifact_found: warn

      - name: Print downloaded control file
        continue-on-error: true
        shell: bash
        run: |
          cat out/control.csv

      - name: execute py script 
        env:
          MASTO_CLIENT_ID: ${{ secrets.MASTO_CLIENT_ID }}
          MASTO_SECRET: ${{ secrets.MASTO_SECRET }}
          MASTO_TOKEN: ${{ secrets.MASTO_TOKEN }}
        run: python mastofeed.py

      - name: Print control file
        shell: bash
        run: |
          cat out/control.csv

      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: control-imported
          path: out/control.csv

      - name: keep alive action
        uses: gautamkrishnar/keepalive-workflow@master     

