name: run mastofeed

on:
  schedule:
    - cron: '1 * * * *' # At *:01 everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script 
        env:
          MASTO_CLIENT_ID: ${{ secrets.MASTO_CLIENT_ID }}
          MASTO_SECRET: ${{ secrets.MASTO_SECRET }}
          MASTO_TOKEN: ${{ secrets.MASTO_TOKEN }}
        run: python mastofeed.py

      - name: commit files
        run: |
          git config --local user.email "lgbaixauli@protonmail.com"
          git config --local user.name "kergozh"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

      - name: keep alive action
        uses: gautamkrishnar/keepalive-workflow@master     

